services:
  - type: web
    name: convertio-app
    env: node
    region: frankfurt
    plan: free
    # ВНИМАНИЕ: Спящий режим через 15 минут неактивности на Free плане
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLOUDCONVERT_KEY
        value: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMTg2NTU3Y2YxNzIzMjQ2M2U5N2ViMjU1NmU2YTA3NzQzYjkzZDY5NWI0YjNmYjFkZjE2NDFiY2M0ODllYmM2Y2ZjNzg3NjUzODdiMGExMjAiLCJpYXQiOjE3NTQ2Mjg2MzguMDk4MjgxLCJuYmYiOjE3NTQ2Mjg2MzguMDk4MjgyLCJleHAiOjQ5MTAzMDIyMzguMDkzMTkyLCJzdWIiOiI3MjYwOTY1MCIsInNjb3BlcyI6WyJ1c2VyLnJlYWQiLCJ1c2VyLndyaXRlIiwidGFzay5yZWFkIiwidGFzay53cml0ZSIsIndlYmhvb2sucmVhZCIsIndlYmhvb2sud3JpdGUiLCJwcmVzZXQucmVhZCIsInByZXNldC53cml0ZSJdfQ.quQWj0jBbt8RVx9VyyCq1-dSU_wWL_V5j5ZRYdzcg9rNCHTNqaUdLRhpWsdYH9luC_evhn-UnvQ-cV0_jsSAOdERiH8F0W7l2SEf0zAMJDpdaCXwYuCBnaQnm8uJf0j6RWr0KLEzvQzIwTUzkt6gkzQoPJQx6-mnjy3NaUAN1zpCS9niMG94dbkrjuluqacLRMru-t_ykl0s7D0GzpolAcaH8NQ0O8iK3VRLXz9c1at62Cc9PxSz5e2op8qRqtrg6vwV7mazoVsfg4tP_qOL0YFdt8MZtZvdgFO4gHVsoyzIVDIfghOddXhaWQYvnY6JMrE0RH-xEyFpyyGHJNw15hLW5D4hM3sHOGYxZj6VNOkguoHjpQ4CG9PsIznTvdaVcdUG3m7KDEjwb9I31UPwjSqXslVCH8Wd_3XyPGTCzug3y0rbGLR2ttqPR-HrzO36mH8HIrVmFNCV1Sv4c71-QtZj8b0dJ23ZsOmHsteFphSub1blh4mW198WkddpyCOf5xYXi21w7hJ6C9zWz0vPLM6QbHjsS6dkwoWm56fYMCNFA_pIhCoeS6FWshLekvWUKSGeU_XWFR4P393Wrt48pG6JOhY8vtmYkpteYOayhkduGo-NV5dAra57H6JV0wiWsPqbAO4-YpfTS5M5CUMh-XYV11M1YA4QdA0WnMsn5JM
    scaling:
      minInstances: 1
      maxInstances: 1
    disk:
      name: convertio-disk
      size: 1GB
      mountPath: /tmp
    healthCheckPath: /api/health